# Generated by Django 3.2.25 on 2025-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_photofile_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='classification_event_enabled',
            field=models.BooleanField(default=False, help_text='Run event detection on photos?'),
        ),
    ]
