# Generated by Django 3.2.25 on 2025-12-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_library_classification_event_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
